Numpy Arrays

In [1]:
my_list = [1,2,3] #Ordinary list

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list) #cast list to array

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_mat #list of lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat) #Creates a matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10, 2) #range min - max : step size

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3)) #Creates an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((5,5)) #Creates an array of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10) #start-stop --> space between points (Different from arange --> step size!S)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4) #Identity matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5) #1D arrays

array([0.56795975, 0.26339004, 0.94936977, 0.8541272 , 0.22776482])

In [20]:
np.random.rand(5,5) #2D arrays

array([[0.42571443, 0.60603937, 0.91186584, 0.22037269, 0.96428266],
       [0.20462495, 0.52030139, 0.33847796, 0.02464271, 0.14904917],
       [0.21085893, 0.02703003, 0.02870015, 0.26887077, 0.21740178],
       [0.90903615, 0.79133463, 0.07592462, 0.2248438 , 0.48572109],
       [0.24852586, 0.85299549, 0.20803897, 0.49635125, 0.84932184]])

In [21]:
np.random.randn(2) #Normal distr.

array([-0.06284701, -0.21132848])

In [22]:
np.random.randn(4,4) #Normal distr. 2D arrays

array([[-0.21476144, -0.30969774,  0.38083042, -0.77409565],
       [ 1.25001734, -0.21414796,  0.92252326,  1.67072152],
       [ 0.27210016,  0.54055926,  0.85576984, -0.52532809],
       [ 0.0468648 , -0.17779848, -1.75876472, -0.23210361]])

In [23]:
np.random.randint(1,100) #Random int from 1 -> 99

60

In [24]:
np.random.randint(1,100,10) #10 random int from 1 -> 99

array([19, 54, 86, 57, 19, 81, 49, 20, 50, 41])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([45, 32, 47, 18, 25, 32,  3, 27, 42, 39])

In [30]:
arr.reshape(5,5) #Reshape the array to 2D array (Need to fill up all spaces!)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max() #Finds max value

47

In [32]:
ranarr.min() #Finds min value

3

In [33]:
ranarr.argmax() #Finds index of max value

2

In [34]:
ranarr.argmin() #Finds index of min value

6

In [36]:
arr.shape #Shows the shape of the data --> 1D --> Notice the call for attribute not method!

(25,)

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape #Shows the shape of the data -->2D --> Notice the call for attribute not method!

(5, 5)

In [40]:
arr.dtype #Shows datatype --> Notice the call for attribute not method!

dtype('int64')

In [42]:
from numpy.random import randint

In [43]:
randint(2,10)

4